export const Userdata=[
    {
        id:10001,
        image:'profile-one.jpg',
        name:'user-name',
        description:'user-detail',
        arrivedTime:10,
        salary:'10k'
    },
    {
        id:10001,
        image:'profile-one.jpg',
        name:'user-name',
        description:'user-detail',
        arrivedTime:10,
        salary:'10k'
    },
    {
        id:10001,
        image:'profile-one.jpg',
        name:'user-name',
        description:'user-detail',
        arrivedTime:10,
        salary:'10k'
    },
    {
        id:10003,
        image:'profile-two.jpg',
        name:'user-name',
        description:'user-detail',
        arrivedTime: 11,
        salary:'10k'
    },
    {
        id:10004,
        image:'profile-four.jpg',
        name:'user-name',
        description:'user-detail',
        arrivedTime:10,
        salary:'30k'
    },
    {
        id:10002,
        image:'profile-two.jpg',
        name:'user-name',
        description:'user-detail',
        arrivedTime: 9,
        salary:'20k'
    },
]